config/routes.rb
Rails.application.routes.draw do
  resources :students do
    member do
      put :create_edit
    end
  end
  resources :users
  resources :sessions
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :user

  validates :name, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  has_secure_password
  before_save { self.email = email.downcase }
  before_save { self.name =  name.titleize }

  has_many :students, dependent: :destroy


  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 100 },
  format: { with: VALID_EMAIL_REGEX, message: 'must be a valid email address' },
  uniqueness: { case_sensitive: false } 

  validates :password, presence: true 
  validates :username, presence: true, uniqueness: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :current_user
  rescue_from ActiveRecord::RecordNotFound, with: :not_found_method

  def not_found_method
    render file: Rails.public_path.join('404.html'), status: :not_found, layout: false
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def require_user_logged_in
    redirect_to new_session_path, flash: { notice: 'Kindly login' } if @current_user.nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user&.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user), flash: { notice: 'Logged In Successfully' }
    else  
      flash[:notice] = 'Invalid Email or Password'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, flash: { notice: 'Log Out Successfully' }
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :username)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def new
    @student = Student.new
    respond_to do |format|
      format.js
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    if @student.update(student_params)
      redirect_to user_path(@current_user), notice: 'Student was successfully updated.'
    else
      render :edit
    end    
  end

  def create_edit
    @student = Student.find_by(name: params[:student][:name], subject: params[:student][:subject])
    if @student
      @student.marks += params[:student][:marks].to_i
      @student.save
      redirect_to user_path(@current_user), notice: 'Student was successfully edited.'
    else
      @student = Student.new(student_params)
      @student.user_id = params[:id]
      @student.save
      redirect_to user_path(@current_user), notice: 'Student was successfully created.'
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to user_path(@current_user), notice: 'Student was successfully deleted.'
  end

  private

  def student_params
    params.require(:student).permit(:name, :subject, :marks, :id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: %i[ show ]

  def new
    @user  = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      redirect_to new_session_path, flash: { notice: 'Sign up successfully' }
    else  
      flash[:notice] = 'Something went wrong'
      render :new
    end
  end

  def show
    @user = @current_user
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :username)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_errors(object, field_name)
    return unless object.errors.any?
    return if object.errors.messages[field_name].blank?

    object.errors.messages[field_name].join(', ')
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeacherPortal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"> 
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partials/flash'%>
    <%= yield %>
  </body>
</html>

app/views/partials/_add_student_modal.html.erb
<div class="modal" tabindex="-1" id="add_student_modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Add Student </h5>
      </div>
      <div class="modal-body">
        <%= form_with model: @student, url: create_edit_student_path(params[:id]), method: :put, remote: true do |form| %>
          <div class="form-group my-3">
            <%= form.label :name, 'Name ' %>
            <%= form.text_field :name, class: "form-control", placeholder: "enter your name" %>
          </div>
          <div class="form-group my-3">
            <%= form.label :subject, 'Subject ' %>
            <%= form.text_field :subject, class: "form-control", placeholder: "enter your subject" %>
          </div>
          <div class="form-group my-3">
            <%= form.label :marks, 'Marks ' %>
            <%= form.text_field :marks, class: "form-control", placeholder: "enter your marks" %>
          </div>
          <div class="modal-footer">
            <%= form.submit "Add", class: "button" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<style>
  .modal {
      position: fixed;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      background-color: #fff;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
      padding: 20px;
      width: 500px;
      height: 500px;
  }

  .modal-dialog {
      margin: 0;
  }

  .modal input[type="text"], .modal input[type="number"] {
      width: calc(100% - 24px);
      padding: 10px;
      margin-bottom: 10px;
      border: 1px solid #ddd;
      border-radius: 4px;
      box-sizing: border-box;
  }

  .modal input[type="text"]:focus, .modal input[type="number"]:focus {
      border-color: #007BFF;
  }

  .modal button {
      width: 100%;
      padding: 10px;
      border: none;
      border-radius: 4px;
      background-color: #333;
      color: white;
      font-size: 16px;
      cursor: pointer;
  }

  .modal button:hover {
      background-color: #555;
  }
  .button{
  background-color: black;
  color: white;
  border: none;
  padding: 10px 50px;
  cursor: pointer;
  font-size: 16px;
  text-decoration: none;
  }
</style>

app/views/partials/_edit_student_modal.html.erb
<div class="modal" tabindex="-1" id="edit_student_modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Edit Student </h5>
      </div>
      <div class="modal-body">
        <%= form_with model: @student  do |form| %>
          <div class="form-group my-3">
            <%= form.label :name, 'Name ' %>
            <%= form.text_field :name, class: "form-control", placeholder: "" %>
          </div>
          <div class="form-group my-3">
            <%= form.label :subject, 'Subject ' %>
            <%= form.text_field :subject, class: "form-control", placeholder: "" %>
          </div>
          <div class="form-group my-3">
            <%= form.label :marks, 'Marks ' %>
            <%= form.text_field :marks, class: "form-control", placeholder: "" %>
          </div>
          <div class="modal-footer">
            <button  class="close-button" data-bs-dismiss="modal">Close</button>
            <%= form.submit "Add", class: "button" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<style>
  .modal {
      position: fixed;
      top: 50%; 
      left: 50%;
      transform: translate(-50%, -50%); 
      background-color: #fff;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
      padding: 20px;
      width: 500px;
      height: 500px;
  }
  .modal-dialog {
      margin: 0;
  }
  .modal input[type="text"], .modal input[type="number"] {
      width: calc(100% - 24px);
      padding: 10px;
      margin-bottom: 10px;
      border: 1px solid #ddd;
      border-radius: 4px;
      box-sizing: border-box;
  }
  .modal input[type="text"]:focus, .modal input[type="number"]:focus {
      border-color: #007BFF;
  }
  .modal button {
      width: 100%;
      padding: 10px;
      border: none;
      border-radius: 4px;
      background-color: #333;
      color: white;
      font-size: 16px;
      cursor: pointer;
  }
  .modal button:hover {
      background-color: #555;
  }
   .button{
    background-color: black;
    color: white;
    border: none;
    padding: 10px 50px;
    cursor: pointer;
    font-size: 16px;
    text-decoration: none;
    }
    .close-button{
    width: 30% !important;
    background-color: black !important;
    }
</style>

app/views/partials/_flash.html.erb
<% if flash.notice %>
  <div class="modal flash-modal" id="flashModal" tabindex="-1" role="dialog" aria-labelledby="flashModalLabel" aria-hidden="true">
    <div class="modal-dialog " role="document">
      <div class="alert alert-success flash-message">
        <div class="text-center">
          <%= flash.notice %>
        </div>
      </div>
    </div>
  </div>
<% end %>
<script>
  $(document).ready(function() {
  $('#flashModal').modal('show');
  setTimeout(function() {
    $('#flashModal').modal('hide');
  }, 2000);
  });
</script>

app/views/students/edit.js.erb
$('body').find('#edit_student_modal').remove();
$('body').append('<%= j (render "partials/edit_student_modal") %>');
$('#edit_student_modal').modal('show');

app/views/students/new.js.erb
$('body').find('#add_student_modal').remove();
$('body').append('<%= j (render "partials/add_student_modal") %>');
$('#add_student_modal').modal('show');

app/views/users/new.html.erb
<div class="login-container">
  <h1>tailwebs.</h1>
  <div class="login-form">
    <%= form_for @user do |form| %>
      <div class="form-group">
        <%= form.label :name, class: 'required' %>
        <%= form.text_field :name, class: "form-control", placeholder: "Enter Your Name" , required: true%>
        <p class='error'><%= show_errors(@user, :name) %></p>
      </div>
      <div class="form-group">
        <%= form.label :username, class: 'required' %>
        <%= form.text_field :username, class: "form-control", placeholder: "Enter Your username" , required: true%>
        <p class='error'><%= show_errors(@user, :usename) %></p>
      </div>
      <div class="form-group">
        <%= form.label :email, class: 'required' %>
        <%= form.email_field :email, class: "form-control", placeholder: "Enter Your Email", required: true%>
        <p class='error'><%= show_errors(@user, :email) %></p>
      </div>
      <div class="form-group">
        <%= form.label :password, class: 'required' %>
        <%= form.password_field :password, class: "form-control", placeholder: "Enter Your Password", required: true%>
        <p class='error'><%= show_errors(@user, :password) %></p>
      </div>
      <div class="form-group">
        <%= form.label :password_confirmation, class: 'required' %>
        <%= form.password_field :password_confirmation, class: "form-control", placeholder: "Confirm Your Password", required: true%>
        <p class='error'><%= show_errors(@user, :password_confirmation) %></p>
      </div>
      <div class="form-group">
        <%= link_to "Already an user? Login", new_session_path %>
      </div>
      <%= form.submit "Sign Up", class: "login-button"  %>
    <% end %>
  </div>
</div>
<style>
  body {
   background-color: #f0f0f0;
   display: flex;
   justify-content: center;
   align-items: center;
   margin: 2rem;
  }
  h1{
     text-align: center;
  }
  .login-form {
   background-color: white;
   padding: 3rem;
   box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
   text-align: center;
   width: 600px;
  }

  h1 {
   color: #e54b4b;
   font-size: 24px;
   margin-bottom: 20px;
  }

  .login-form .form-group {
   margin-bottom: 15px;
  }

  .login-form label {
   display: block;
   text-align: left;
   font-weight: bold;
   margin-bottom: 5px;
  }

  .login-form input[type="text"],
  .login-form input[type="password"],
  .login-form input[type="email"]  {
   width: 100%;
   padding: 10px;
   margin-top: 5px;
   border: 1px solid #ccc;
   border-radius: 4px;
   box-sizing: border-box;
  }

  .forgot-password {
   display: block;
   text-align: right;
   margin-top: 10px;
   font-size: 12px;
   color: #007bff;
   text-decoration: none;
  }

  .forgot-password:hover {
   text-decoration: underline;
  }

  .login-button {
   padding: 0.6rem 3rem;
   background-color: #333;
   color: white;
   border: none;
   cursor: pointer;
  }

  .login-button:hover {
   background-color: #555;
  }
</style>

app/views/users/show.html.erb
<div class="header">
  <h1>tailwebs.</h1>
  <div class="nav-links">
    <a href="#">Home</a>
    <a> <%= button_to "Logout", session_path(@current_user), method: :delete, class: "logout-link" %></a>
  </div>
</div>
<div class="table-container">
  <% if @user.students.count != 0 %>
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Subject</th>
          <th>Mark</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% @user.students.each do |student| %>
          <tr>
            <td><span class="avatar"><%= student.name[0].upcase %></span> <%= student.name %></td>
            <td><%= student.subject %></td>
            <td><%= student.marks %></td>
            <td>
              <div class="dropdown">
                <button class="dropbtn">⋮</button>
                <div class="dropdown-content">
                  <%= link_to "Edit", edit_student_path(id: student.id), remote: true, class: "" %>
                  <%= button_to "Delete", student_path(id: student.id), method: :delete, class: "logout-link" %>
                </div>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <b>No student listed, click on Add to create students</b><br>
    <br>
  <% end %>
  <%= link_to "Add", new_student_path(id: @user.id), remote: true, class: "add-button" %>
</div>
<style>
  body {
  background-color: #f0f0f0;
  font-family: Arial, sans-serif;
  margin: 0;
  padding: 0;
  display: flex;
  flex-direction: column;
  align-items: center;
  }

  .header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  width: 100%;
  padding: 20px;
  background-color: white;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  }

  .header h1 {
  color: #e54b4b;
  margin: 0;
  }
  .nav-links{
  display: flex;
  margin-right: 10px;
  }

  .nav-links a {
  margin-left: 20px;
  text-decoration: none;
  color: black;
  font-weight: bold;
  }

  .table-container {
  padding: 20px;
  margin: 20px;
  border-radius: 8px;
  width: 90%;
  max-width: 1000px;
  }

  table {
  width: 100%;
  margin-bottom: 40px;
  background-color: white;

  }


  th, td {
  padding: 12px 15px;
  text-align: left;
  border-bottom: 1px solid #ddd;
  }

  th {
  font-weight: bold;
  }

  tbody tr:hover {
  background-color: #f1f1f1;
  }

  .avatar {
  background-color: #007bff;
  color: white;
  border-radius: 50%;
  display: inline-block;
  width: 30px;
  height: 30px;
  line-height: 30px;
  text-align: center;
  margin-right: 10px;
  }

  .dropdown {
  position: relative;
  display: inline-block;
  }

  .dropbtn {
  background: none;
  border: none;
  font-size: 20px;
  cursor: pointer;
  }

  .dropdown-content {
  display: none;
  position: absolute;
  background-color: white;
  min-width: 100px;
  box-shadow: 0 8px 16px rgba(0, 0, 0, 0.1);
  z-index: 1;
  }

  .dropdown-content a {
  color: black;
  padding: 8px 12px;
  text-decoration: none;
  display: block;
  }

  .dropdown-content a:hover {
  background-color: #f1f1f1;
  }

  .dropdown:hover .dropdown-content {
  display: block;
  }

  .add-button {
  background-color: black;
  color: white;
  border: none;
  padding: 10px 50px;
  margin-top: 5rem;
  cursor: pointer;
  font-size: 16px;
  text-decoration: none;
  }

  .add-button:hover {
  background-color: #333;
  }

  .logout-link {
    background: none;
    border: none;
    padding: 0;
    font: inherit;
    cursor: pointer;
    display: inline;
  }
</style>